# Generated by Django 5.1 on 2025-04-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_pollvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Onaylandı mı?'),
        ),
        migrations.AddField(
            model_name='rating',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Onaylandı mı?'),
        ),
    ]
