# Generated by Django 5.1 on 2025-04-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_like_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='points_added',
            field=models.BooleanField(default=False, verbose_name='Puan Eklendi mi?'),
        ),
        migrations.AddField(
            model_name='like',
            name='points_added',
            field=models.BooleanField(default=False, verbose_name='Puan Eklendi mi?'),
        ),
        migrations.AddField(
            model_name='post',
            name='points_added',
            field=models.BooleanField(default=False, verbose_name='Puan Eklendi mi?'),
        ),
        migrations.AddField(
            model_name='rating',
            name='points_added',
            field=models.BooleanField(default=False, verbose_name='Puan Eklendi mi?'),
        ),
    ]
