# Generated by Django 5.1 on 2025-05-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comment_points_added_like_points_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollvote',
            name='points_added',
            field=models.BooleanField(default=False),
        ),
    ]
