# Generated by Django 5.1 on 2024-09-09 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={},
        ),
    ]
