# Generated by Django 5.1 on 2024-10-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_progress_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Grup Seviyesi'),
        ),
    ]
