# Generated by Django 5.1 on 2025-04-28 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_group_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Soru')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Anket Sorusu',
                'verbose_name_plural': 'Anket Soruları',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Tamamlandı mı?')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey_completion', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Anket Tamamlama',
                'verbose_name_plural': 'Anket Tamamlamalar',
            },
        ),
        migrations.CreateModel(
            name='UserSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(choices=[(1, 'Kesinlikle katılmıyorum'), (2, 'Katılmıyorum'), (3, 'Kısmen katılmıyorum'), (4, 'Kısmen katılıyorum'), (5, 'Katılıyorum'), (6, 'Kesinlikle katılıyorum')], verbose_name='Cevap')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cevap Tarihi')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='users.initialsurvey', verbose_name='Soru')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Cevabı',
                'verbose_name_plural': 'Kullanıcı Cevapları',
                'unique_together': {('user', 'question')},
            },
        ),
    ]
