# Generated by Django 5.1 on 2025-04-28 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_initialsurvey_surveycompletion_usersurveyresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='is_team_based',
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Takım Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Takım Açıklaması')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='users.group', verbose_name='Grup')),
            ],
            options={
                'verbose_name': 'Takım',
                'verbose_name_plural': 'Takımlar',
                'unique_together': {('name', 'group')},
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='users.team'),
        ),
    ]
