# Generated by Django 5.1 on 2025-04-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_group_is_team_based_team_customuser_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_team_based',
            field=models.BooleanField(default=False, verbose_name='Takım Bazlı mı?'),
        ),
    ]
