# Generated by Django 5.1 on 2025-04-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_group_is_team_based'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersurveyresponse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='surveycompletion',
            name='second_survey_completed',
            field=models.BooleanField(default=False, verbose_name='İkinci Anket Tamamlandı mı?'),
        ),
        migrations.AddField(
            model_name='surveycompletion',
            name='second_survey_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='İkinci Anket Tamamlanma Tarihi'),
        ),
        migrations.AddField(
            model_name='surveycompletion',
            name='second_survey_reminder_sent',
            field=models.BooleanField(default=False, verbose_name='İkinci Anket Hatırlatması Gönderildi mi?'),
        ),
        migrations.AddField(
            model_name='usersurveyresponse',
            name='is_second_response',
            field=models.BooleanField(default=False, verbose_name='İkinci Cevap mı?'),
        ),
        migrations.AlterUniqueTogether(
            name='usersurveyresponse',
            unique_together={('user', 'question', 'is_second_response')},
        ),
    ]
