"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(^eqxpe@+hg+e9!@d8tanbdwg8z1xxc0nl0_)s#rh6jsv5pf24'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "users",
    "pages",
    'posts',
    'support',
    'scoreboards',
    "django_extensions",
    'django_celery_beat',
    'django_celery_results',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

# Sonuçlar için veritabanı backend kullanma
CELERY_RESULT_BACKEND = 'django-db'

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'users.context_processors.navbar_context'
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_USER_MODEL = 'users.CustomUser'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# Dil ayarı
LANGUAGE_CODE = 'tr'

# Zaman dilimi ayarı (Türkiye)
TIME_ZONE = 'Europe/Istanbul'

# Uluslararasılaştırma ve yerelleştirme ayarları
USE_I18N = True  # Uluslararasılaştırma (Internationalization) etkin
USE_L10N = True  # Yerelleştirme (Localization) etkin
USE_TZ = True    # Zaman dilimi etkin

# Django'nun yerel tarih ve saat formatlarını kullanmasını sağlamak için
DATETIME_FORMAT = 'd-m-Y H:i:s'
DATE_FORMAT = 'd-m-Y'
TIME_FORMAT = 'H:i:s'



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Static dosyaların toplandığı yer (production için)

# Media dosyaları (Kullanıcı tarafından yüklenen içerikler) için ayarlar
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


JAZZMIN_SETTINGS = {
    "site_title": "Board Yönetim Paneli",
    "site_header": "Bord Yönetimi",
    "site_brand": "Board Mobil",
    "welcome_sign": "Hoş Geldiniz Board Mobil App Yönetim Paneline",
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": ["auth", "books", "books.author", "books.book"],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    "custom_links": {
        "footer": [
            {
                "name": "Board Mobil App",
                "url": "https://example.com",  # Footer'a eklemek istediğiniz URL
                "icon": "fas fa-link",  # İkon sınıfı (Font Awesome kullanılır)
                "permissions": ["auth.view_user"],  # Linki görmek için gereken izinler
            },
            {
                "name": "Hakkında",
                "url": "https://example.com/about",
                "icon": "fas fa-info-circle",
                "permissions": ["auth.view_user"],
            },
        ],
    },
    "site_brand_footer": "© 2024 Board Mobil App",  
        "footer": "© 2024 Board Mobil App - All Rights Reserved",

}

JAZZMIN_UI_TWEAKS = {
    "navbar": "navbar-dark",  # Navbar arka planı için koyu tema
    "theme": "flatly",  # Genel tema
    "dark_mode_theme": "darkly",  # Karanlık mod teması
    "primary_color": "#ff7f0e",  # Turuncu renk
    "accent": "orange",  # Accent rengi
    "button_classes": {
        "primary": "btn btn-warning",  # Turuncu butonlar
        "secondary": "btn btn-secondary",
        "info": "btn btn-info",
        "warning": "btn btn-warning",  # Turuncu uyumlu renk
        "danger": "btn btn-danger",
        "success": "btn btn-success",
    },
    "sidebar": "sidebar-light-orange",  # Yan menü için turuncu ton
    "brand_colour": "orange",  # Marka alanı için turuncu
    "navbar_fixed": True,  # Navbar sabit
    "sidebar_fixed": True,  # Yan menü sabit
}
