# Generated by Django 5.1 on 2025-02-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportrequest',
            name='category',
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='support_attachments/', verbose_name='Dosya Eki'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='Mesaj İçeriği'),
        ),
    ]
