# Generated by Django 5.1 on 2024-08-23 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name': 'Yarışma', 'verbose_name_plural': 'Yarışma'},
        ),
        migrations.AlterModelOptions(
            name='scoreboard',
            options={'ordering': ['-score'], 'verbose_name': 'Skor Tablosu', 'verbose_name_plural': 'Skor Tablosu'},
        ),
    ]
